using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Xunit;

namespace EntityLengths.Generator.Tests;

public class EntityMaxLengthGeneratorTests
{
    private readonly CSharpGeneratorDriver _driver;

    public EntityMaxLengthGeneratorTests()
    {
        var generator = new EntityMaxLengthGenerator();
        _driver = CSharpGeneratorDriver.Create(generator);
    }

    private static class TestSources
    {
        public const string FluentApiEntity =
            @"
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace TestNamespace;

public class User
{
    public required string Name { get; set; }
}

public class UserConfiguration : IEntityTypeConfiguration<User>
{
    public void Configure(EntityTypeBuilder<User> builder)
    {
        builder.Property(p => p.Name).HasMaxLength(50).IsRequired();
    }
}";

        public const string DataAnnotationsEntity =
            @"
using System.ComponentModel.DataAnnotations;

namespace TestNamespace;

public class User
{
    [MaxLength(50)]
    public required string Name { get; set; }
}";

        public const string ExpectedOutput =
            @"// <auto-generated/>
namespace EntityMaxLengthGeneratorTests;

public static partial class EntityLengths 
{
	public static partial class User
	{
		public const int NameLength = 50;
	}
}
";
    }

    private static class CompilationBuilder
    {
        public static CSharpCompilation CreateCompilation(
            string sourceCode,
            bool includeDataAnnotations = false
        )
        {
            var references = new List<MetadataReference>
            {
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
            };

            if (includeDataAnnotations)
            {
                var runtimePath = Path.Combine(
                    RuntimeEnvironment.GetRuntimeDirectory(),
                    "System.Runtime.dll"
                );
                references.Add(MetadataReference.CreateFromFile(runtimePath));
                references.Add(
                    MetadataReference.CreateFromFile(typeof(MaxLengthAttribute).Assembly.Location)
                );
            }

            return CSharpCompilation.Create(
                nameof(EntityMaxLengthGeneratorTests),
                [CSharpSyntaxTree.ParseText(sourceCode)],
                references,
                new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)
            );
        }
    }

    private static class GeneratorTestHelper
    {
        private static string GetGeneratedOutput(GeneratorDriverRunResult runResult)
        {
            var syntaxTree = runResult.GeneratedTrees.Single(t =>
                t.FilePath.EndsWith("EntityLengths.g.cs")
            );

            return syntaxTree.GetText().ToString();
        }

        public static void AssertGeneratedOutput(
            GeneratorDriverRunResult runResult,
            string expectedOutput
        )
        {
            var actualOutput = GetGeneratedOutput(runResult);

            Assert.Equal(expectedOutput.ReplaceLineEndings(), actualOutput.ReplaceLineEndings());
        }
    }

    [Fact]
    public void Generate_EntityLength_With_FluentApi()
    {
        // Arrange
        var compilation = CompilationBuilder.CreateCompilation(TestSources.FluentApiEntity);

        // Act
        var result = _driver.RunGenerators(compilation).GetRunResult();

        // Assert
        GeneratorTestHelper.AssertGeneratedOutput(result, TestSources.ExpectedOutput);
    }

    [Fact]
    public void Generate_EntityLength_With_DataAnnotations()
    {
        // Arrange
        var compilation = CompilationBuilder.CreateCompilation(
            TestSources.DataAnnotationsEntity,
            includeDataAnnotations: true
        );

        // Act
        var result = _driver.RunGenerators(compilation).GetRunResult();

        // Assert
        GeneratorTestHelper.AssertGeneratedOutput(result, TestSources.ExpectedOutput);
    }
}
